Clarifai/clarifai-python

clarifai/client/client.py

Recent changes to support Python 3 broke handling for unicode URLs,
since unicode strings are not instances of str in Python 2.

Fix unicode URL handling.

---

clarifai/client/__init__.py
clarifai/client/client.py
tests/test_client.py

Reverts Clarifai/clarifai-python#17

Revert "refer to the server for languages"

---

setup.py

A user reported issues importing the client because he didn't have the
'six' module installed. I added this to the install requirements in
setup.py.

Add 'six' to requirements.

---

clarifai/rest/client.py

Give some extra insight as to what's happening during model fetch failure: https://github.com/Clarifai/clarifai-python/issues/76

Bubble up other types of ApiErrors during model fetch

---

.isort.cfg
clarifai/rest/__init__.py
clarifai/rest/client.py
tests/rest_tests/test_models.py
tests/unit_tests/test_inputs.py
tests/unit_tests/test_model.py
tests/unit_tests/test_search_models.py

These will be deprecated in coming week. See https://docs.clarifai.com/product-updates/upcoming-api-changes for more details on the Face proto deprecation and the `facedetect*` model type cleanup.

[TT-544]: remove Face object and facedetect* model types

---

clarifai/rest/client.py
tests/rest_tests/test_workflow.py

Remove public_workflows endpoint. Users should rely on docs to get any public workflows or see them in the list when creating applications in Portal.

[TT-791]: remove public workflows endpoint from client

---

tests/rest_tests/test_api.py

Currently in backend, we strictly limit the API Key to be 32 character length hex encoded string.
So, update the client test to reflect this limitation.

fix invalid api key test

---

.travis.yml
tests/rest_tests/test_video.py

video frame timestamp will be midpoint time.
for example when sample_ms is 2000,
previously we return the frame time as:
0s, 2s, 4s ...
now we change to:
1s, 3s, 5s....
Making this change so the time is more accurate since ffmpeg using the midpoint.

shift frame time

---

tests/rest_tests/test_public_models.py

Remove the test for the people-segmentation model from testPublicModels as we'd like to take it down.

remove test for people-segmentation model

---

.github/workflows/run_tests.yml
tests/requirements.txt
tests/test_auth.py
tests/test_stub.py

- This workflow will install Python dependencies, run tests and lint with a variety of Python versions
- Added the existing unit tests from clarifai-python-utils for Auth and Stub

[DEVX:176] setup automated tests

---

README.md
clarifai/client/app.py
clarifai/client/dataset.py
clarifai/client/model.py
clarifai/client/workflow.py
tests/test_workflow_predict.py

- Added functionality to interface with Workflows(predict, list, versions)
```python
from clarifai.client.workflow import Workflow
workflow = Workflow(user_id="user_id", app_id="app_id", workflow_id="model_id")
workflow_prediction = workflow.predict_by_url(url="url", input_type="image") # Supports image, text, audio, video
workflow = Workflow(user_id="user_id", app_id="app_id", workflow_id="workflow_id",
output_config={"min_value": 0.98}) # Return predictions having prediction confidence > 0.98
workflow_prediction = workflow.predict_by_filepath(filepath="local_filepath", input_type="text") # Supports image, text, audio, video
```
```python
all_workflow_versions = workflow.list_versions()
workflow_v1 = Workflow(workflow_id="workflow_id", workflow_version=dict(id="workflow_version_id"), …
```

[DEVX:122] Added Workflow Interface

---

README.md
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/user.py

- Text upload from CSV, folder
- Creating app with workflow id
```python
from clarifai.client.user import User
client = User(user_id="user_id")
app = client.create_app(app_id="demo_app")
dataset = app.create_dataset(dataset_id="demo_dataset")
#upload text from csv
dataset.upload_from_csv(csv_path='csv_path', labels=True)
#upload data from folder
dataset.upload_from_folder(folder_path='folder_path', input_type='text', labels=True)
```
- While creating app, default workflow_id is set as 'Language-Understanding' for now(Temporary, will revert to empty workflow after hackathon)
- TODO: upload image_URLs from csv

[DEVX-131] Text_upload

---

.readthedocs.yaml

- Experimenting to setup Sphinx docs(ref [clarifai-sdk-v2](https://clarifai-python.readthedocs.io/en/latest/index.html))

added readthedocs yaml

---

clarifai/datasets/upload/utils.py

- Added dynamic import of local dir dataset class, so that users doesn't have to reintialise the class eachtime
```python
from clarifai.client.dataset import Dataset
d.upload_dataset("visual_clf", "train", "module_dir_path")
d.upload_dataset("visual_detection", "train", "module_dir_path")
```

[DEVX-198]: Fix Dataset import cache bug

---

clarifai/datasets/export/dataset_inputs.py

**Problem**
When using `clarifai.datasets.export.dataset_inputs.InputDownloader` on a local archive with image URLs, the following error is raised:
> OSError: cannot write mode RGBA as JPEG
[This](https://stackoverflow.com/questions/48248405/cannot-write-mode-rgba-as-jpeg) slackoverflow post proposes to use something like PNG instead to account for the A (transparency) channel of the images.
**Tests**
Locally tested and passing. To replicate, create a dataset version export (protobuf) and run the following snippet:
```python
import requests
from clarifai.datasets.export.dataset_inputs import DatasetExportReader, InputDownloader
metadata = 'Key API_KEY'
def main():
local_archive_path = "FULL_PATH_TO_ZIP"
save_path = "output.zip"
session = requests.Session() …
```

🐛 Fix dataset export image format

---

.pre-commit-config.yaml
tests/test_model_predict.py

- Add test case for model prediction for raw text
- Act as extra examples for how to inference on raw text by encoding to UTF-8

Add model predict test case for raw text

---

README.md
clarifai/client/dataset.py
clarifai/datasets/export/inputs_annotations.py

- Support for Annotation Download
- creates a json file(filename being same) storing concepts/regions for each input irrespective of its type (image, text)/(cls, det, seg, text-cls)
- Multithreading Support 
- Retries for failed requests
Downloaded Folder structure
```lua
|-- {split} Root Folder
|   |-- Inputs Subfolder
|   |   |-- Input Files
|   |
|   |-- Annotations Subfolder
|       |-- JSON Annotation Files
```
```python
from clarifai.client.dataset import Dataset
Dataset().export(save_path='output.zip', local_archive_path='clarifai-data-protobuf.zip')
```

[DEVX-232]: Support Annotations Download

---

.github/workflows/run_tests.yml

https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git
- to allow external PRs to run against workflow and code from the base of the PR

Add pull_request_target to workflow

---

setup.py

Hi from the https://github.com/chroma-core/chroma team. 
There is a minor alignment between setup.py and requirements.txt, as this seems to be causing an issue with `clarifai` and `chromadb` packages co-existence.

[BUG]: Aligned setup.py requirements with requirements.txt

---

README.md
clarifai/client/base.py
clarifai/client/model.py
clarifai/client/workflow.py
tests/test_app.py
tests/test_model_predict.py
tests/workflow/test_create_delete.py

```python
from clarifai.client.model import Model
"""
Get Model information on details of model(description, usecases..etc) and info on training or
"""
gpt_4_model = Model("https://clarifai.com/openai/chat-completion/models/GPT-4")
print(gpt_4_model)
model_prediction = gpt_4_model.predict_by_bytes(b"Write a tweet on future of AI", "text", inference_params=dict(temperature=str(0.7), max_tokens=30))
model_prediction = model.predict_by_filepath(filepath="local_filepath", input_type, output_config={"min_value": 0.98}) # Supports image, text, audio, video
video_input_proto = [input_obj.get_input_from_url("Input_id", video_url=BEER_VIDEO_URL)]
model_prediction = model.predict(video_input_proto, input_type="video", output_config={"sample_ms": 2000})
```

Add inference params Support in Model Predict

---

.github/workflows/run_tests.yml
clarifai/client/search.py
clarifai/schema/search.py
tests/test_data_upload.py
tests/test_search.py

- Add support for `PostInputsSearch`
- Supports Inputs Search by `input_types`, `input_dataset_ids`, `input_status_code`
```python
from clarifai.client.search import Search
search = Search(user_id='user_id', app_id='app_id', top_k=10, metric='cosine')
res = search.query(filters=[{'input_types': ['image', 'text']}, {'input_status_code': 30000}])
```
- Added unit tests for the same

Support Input Filters in Search

---

clarifai/client/app.py
clarifai/client/dataset.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/user.py
clarifai/client/workflow.py

-  Fix BaseURL info not passing down to other resources
- Now users can be able to do
```python
user = User(user_id = user_id, base_url = base_url)
app = user.app(app_id = app_id)
model = app.model(model_id = model_id,model_version_id = version_id)
```

[DEVX-289]: Fix passing BaseURL info

---

requirements.txt
setup.py

Relax pandas, numpy, pyyaml, pillow, rich versions 
change pycocotools to extras_require (`pip install "clarifai[all]"`)

change pycocotools to extras require

---

clarifai/client/app.py
clarifai/client/base.py
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/runner.py
clarifai/client/search.py
clarifai/client/user.py
clarifai/client/workflow.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/text.py
clarifai/utils/misc.py
tests/test_app.py
tests/test_model_predict.py
tests/workflow/test_predict.py

- Support `PAT` as parameter while initialising resources in addition to setting as env variable
- Changed necessary methods in `Inputs` class to staticmethods
```python
model = Model(url="https://clarifai.com/openai/chat-completion/models/GPT-3_5-turbo", pat="CLARIFAI_PAT")
print(model.predict_by_bytes(b"Hello World", "text"))
```
- Initialised respective `User`, `App`, `Model`, `Workflow` classes w.r.t `PAT` in `test_app.py`, `test_model_predict.py` and `workflow/test_predict.py`

[DEVX-300] Support PAT as arg

---

clarifai/utils/logging.py
tests/test_misc.py

- Fixes #220 
- Instead of adding `RichHandler` to root logging, now it is being added to SDK specific loggers
- Added test_misc.py for the same

[Bug] Fix root logger handler

---

requirements.txt

As far as I can tell, pytest is not a necessary requirement for the library itself.
It's already included in tests/requirements.txt, and in fact, is overridden (from ==7.4.1 in requirements.txt to ==7.1.2 in tests/requirements.txt) in the `Run tests` GitHub Actions workflow (e.g. https://github.com/Clarifai/clarifai-python/actions/runs/6970572930/job/18968766681#step:4:179).

Remove pytest requirement

---

requirements.txt

As far as I can tell, OmegaConf is not used at all anymore in the library.
It seems to have been added as a requirement for a singular usage in `clarifai_utils/data_upload/upload.py` in https://github.com/Clarifai/clarifai-python/commit/c3cf0d6dec57247a800bad1430bb1b4979c722c1.
That usage was later removed in https://github.com/Clarifai/clarifai-python/commit/0685e60c7eaf1d2bb7714518de49ad3d886dddd4, and the file itself was removed entirely in https://github.com/Clarifai/clarifai-python/commit/0f292bc098bf7ae590fab6c68304b978547fe4ff.

Remove OmegaConf requirement

---

.github/workflows/publish.yml
.github/workflows/run_tests.yml
setup.py

Hello,
I believe it would be nice to make sure that modern Python versions are supported by the Clarifai Python SDK, so I'd like to suggest changes that:
* enable testing for Python 3.10-3.12 on CI
* add corresponding [classifiers](https://pypi.org/classifiers/) to `setup.py`
* bump `actions/checkout` to [v4](https://github.com/actions/checkout/releases/tag/v4)
* bump `actions/setup-python` to [v4](https://github.com/actions/setup-python/releases/tag/v4)
Best regards!

Ensure support for Python 3.10-3.12

---

clarifai/client/input.py

Support multimodal inputs for inference without using private methods
```diff
from clarifai.client.model import Model
from clarifai.client.input import Inputs
prompt = "What time of day is it?"
image_url = "https://samples.clarifai.com/metro-north.jpg"
inference_params = dict(temperature=0.2, max_tokens=100)
-text_pb = Inputs.get_input_from_bytes("", text_bytes=prompt.encode()).data.text
-image_pb = Inputs.get_input_from_url("", image_url= image_url).data.image
model_prediction = Model("https://clarifai.com/openai/chat-completion/models/openai-gpt-4-vision").
-    predict(inputs = [Inputs._get_proto(input_id="",imagepb=image_pb,text_pb=text_pb)],
+    predict(inputs = [Inputs.get_multimodal_input(input_id="",image_url=image_url, raw_text=prompt)],
inference_params=inference_params) …
```

Support multimodal inputs for inference

---

clarifai/client/search.py
clarifai/schema/search.py
tests/test_search.py

- To support Rank based search in PostInputsSearch
- Added `test_rank_filter_search` test case
```python
from clarifai.client.search import Search
search = Search(user_id="sai_nivedh", app_id="test-imdb", top_k=3, metric="cosine")
results = search.query(ranks=[{"text_raw": "Movie is Awesome"}], filters=[{"input_types": ["text"]}])
for data in results:
for hit in data.hits:
print(hit.input.id)
```

[DEVX-322] Add Rank to PostInputsSearch

---

clarifai/client/app.py
clarifai/urls/helper.py
tests/workflow/fixtures/single_branch_with_public_cropper_model_and_latest_version.yml

**Problem**
Users should be able to use the web URL e.g. `"https://clarifai.com/Isaac/let-me-see-if-this-works1"` to instantiate an App object.
Code snippet used:
```python
from clarifai.client.app import App
app = App("https://clarifai.com/Isaac/let-me-see-if-this-works1")
```
Actual Behaviour:
```
In [6]: app = App("https://clarifai.com/Isaac/let-me-see-if-this-works1")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /Users/isaacchung/virtualenv/v1/lib/python3.10/site-packages/clarifai/client/app.py:50 in        │
│ __init__ …
```

Use specific URL method for apps

---

README.md

The old demo link was replaced with the new one.

changed Demo link

---

clarifai/client/workflow.py
clarifai/rag/rag.py
clarifai/rag/utils.py
tests/test_rag.py

The chat method for RAG follows the openAI API format, i.e. it [expects messages as a list of dicts](https://docs.anthropic.com/claude/reference/messages_post) like:
```
[
{"role": "user", "content": "Hello there."},
{"role": "assistant", "content": "Hi, I'm Claude. How can I help you?"},
{"role": "user", "content": "Can you explain LLMs in plain English?"},
]
```
This aligns with most if not all cloud LLM providers in terms of format.
- Users can choose whether to manage chat state themselves or let us do it.
- Added workflow state support in workflow predict
- work is in progress for the actual backend change for `client_manage_state=false`. May consider adding "not implemented" for the moment and a test XFAIL

Add RAG chat method

---

README.md
clarifai/client/input.py
tests/test_data_upload.py

- Download inputs feature(SDH)
```python
#listing inputs
input_generator = input_obj.list_inputs(page_no=1,per_page=1,input_type='image')
inputs_list = list(input_generator)
#downloading_inputs
input_bytes = input_obj.download_inputs(inputs_list)
with open('demo.jpg','wb') as f:
f.write(input_bytes[0])
```
- Unit test and readme changes for the same.

[DEVX-324]: Download inputs

---

clarifai/rag/rag.py

Missed check. Current behaviour:
```
In [15]: RAG.setup()
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /Users/isaacchung/work/clarifai-python/clarifai/rag/rag.py:65 in setup                           │
│                                                                                                  │
│    62 │   │   >>> rag_agent = RAG.setup()                                                        │
│    63 │   """                                                                                    │
│    64 │   if not user_id: …
```

Assert user_id for `RAG.setup()`

---

clarifai/client/base.py

**Description :**
list_inputs function is not fetching metadata field since the process_response_keys function which used to convert the input response into object omits it. 
**Changes made :** 
- Modified the function to include metadata fields as well. 
- Tested with other functions which call this internally such as, list_workflows, list_apps, list_datasets, list_modules, list_models, list_annotations, list_concepts.
https://clarifai.atlassian.net/browse/DEVX-330

DEVX-330 - modified process_response_keys function to support metadata fields

---

tests/test_model_train.py

- Test cases are failing due to a change made to replace the names of custom config templates. refer (https://github.com/Clarifai/clarifai/pull/17210/files).
- Modified the name in script tests/test_model_train.py
- Jira ticket : https://clarifai.atlassian.net/browse/DEVX-336

Rename MMClassification config templates to have _AdvancedConfig

---

README.md
clarifai/rag/rag.py
tests/test_rag.py

When users have an existing app with inputs, they currently do not have a way to start RAG via the RAG class. The setup method supports creating everything, including the app, from scratch. But it is possible that the data ingestion phase is too large to be replicated.
Add a parameter and checks in the `setup` method. Preview:
```python
from clarifai.rag import RAG
rag_agent = RAG.setup(app_url=YOUR_APP_URL)
rag_agent.chat(messages=[{"role":"human", "content":"What is Clarifai"}])
```

Support case when existing app without workflow is provided

---

README.md

**What does this PR do?**
Adds/makes the amendment for right/working steps to install `clarifai` python package from source. 
**What is the ticket/issue associated with this PR?**
No ticket as I am posing as an Open-Source Contributor, rather than a Clarifai team/group member on Github.
**If None, add the motivation behind this PR?**
As I was experimenting with Clarifai upon my discovery of this awesome utility/ML tool, I realised contributing to Clarifai code base as a great idea. Thereafter, upon trying to install the clarifai cli from source, I realised that the steps had one line-of-code missing (or may be written better/crisper, as I have explained in the "Additional Notes"
The changes by-and-large allude towards the usage of `python setup.py install` as an additional/legitimate …

right step to install clarifai from source

---

README.md
clarifai/client/app.py
clarifai/client/dataset.py
clarifai/datasets/export/inputs_annotations.py

* Dataset version ID support in 
* `app.dataset()`
* `Dataset()`
* Dataset.list_versions() improvement
* README change for dataset.export()
* Improved log messages for Dataset Export.
* Added version_id param in Dataset class and app.dataset function
* Removed redundant info for list_versions() 
- Existing tests cover this

[DEVX-396]: Dataset Version ID support

---

clarifai/utils/model_train.py

* This PR mainly focussed on addressing the concern raised in this ticket https://clarifai.atlassian.net/browse/DEVX-381.
* Removed the key `base_embed_model` from params.yaml file, since the model training by default considers the base embed model which is set for the app and no need to define it again in params file.
* Added `concepts_mutually_exclusive` parameter which is there in UI but missing from the existing yaml template.
* Test was done with curl endpoint which fetches the model training info after it was trained.
```bash
curl -X GET "https://api.clarifai.com/v2/users/mogith-p-n/apps/transfer_learn/models/image_transfer_learn/versions/b9c41a42a29e4f639d7eacf115c2e3fe" \
-H "Authorization: Key PAT"
```
Response
```
{"status":{"code":10000,"description":"Ok","req_id":"501d3c2f1740e …
```

[DEVX-381]: Modified train params.yaml file structure

---

clarifai/client/base.py
clarifai/client/model.py

* To remove constraint of user specifying `model_type_id` for `training_logs`
* Make use of `load_info()` to get model version details
* Existing training status tests should pass
*

[DEVX-399] Fix training status bug

---

MANIFEST.in

These files aren't currently being included in the sdist, giving e.g.
```
$ python setup.py --help
...
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION'
```
Looks like this has been an issue since 9.9.1.
This also means you can't use the more recent `pypa/build` module to build a wheel for this package:
```
$ python -m build
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- setuptools >= 40.8.0
* Getting build dependencies for sdist...
* Building sdist...
...
copying files to clarifai-10.2.1...
copying LICENSE -> clarifai-10.2.1
copying MANIFEST.in -> clarifai-10.2.1
copying README.md -> clarifai-10.2.1
copying pyproject.toml -> clarifai-10.2.1
copying setup.py -> clarifai-10.2.1
...
* Building wheel from sdist
* Creating …
```

Add VERSION and requirements.txt to setup.py

---

clarifai/utils/logging.py
tests/test_misc.py

Added a json logger so it's convenient to get logs into logging stacks. Logs will look like: 
```
{"msg": "Loop iteration: 0 for thread 140485041844224", "@timestamp": "2024-09-24T21:31:15.411793Z", "filename": "test.py", "stack_info": null, "lineno": 214, "level": "info", "req_id": "runner-084a853704604c948bf226911f3cb0c6", "orig_req_id": "runner-084a853704604c948bf226911f3cb0c6"}
```
when env var `ENABLE_JSON_LOGGER=true`

[EAGLE-4201]: json logging

---

clarifai/utils/logging.py

If ENABLE_JSON_LOGGER is 'true' then definitely use json logger.
If ENABLE_JSON_LOGGER is 'false' then definitely don't use json logger.
If ENABLE_JSON_LOGGER is not set, then use json logger if in k8s.

[EAGLE-4201]: use json logger always in k8s.

---

clarifai/client/auth/helper.py

New versions of streamlit lead to error text boxes when using the removed st.experimental_get_query_params() call. It has been replaced by st.query_params which is not callable, so it's passed to a dict to replicate the functionality.

fixing streamlit query_params call to remove error w/streamlit >=1.30

---

CHANGELOG.md

- Added tests for CRUD Operations of CO Resource - Deployment [(#431)] (https://github.com/Clarifai/clarifai-python/pull/431)
- Added request-id-prefix header to SDK requests to improve SDK monitoring [(#430)] (https://github.com/Clarifai/clarifai-python/pull/430)
- Added CLI for Model upload [(#429)] (https://github.com/Clarifai/clarifai-python/pull/429)
- Fixed model servicer for Model Upload [(#428)] (https://github.com/Clarifai/clarifai-python/pull/428)
- Added python versions badge to README.md [(#427)] (https://github.com/Clarifai/clarifai-python/pull/427)
- Removed stream tests till stream API is fixed [(#426)] (https://github.com/Clarifai/clarifai-python/pull/426)
- Removed unnecessary prefixes to concept ID added from SDK [(#424)] …

version_10.9.3

---

CHANGELOG.md

version_10.9.4

---

clarifai/cli/model.py
clarifai/runners/models/model_run_locally.py

If I do not make a change in requirements.txt, then there should be no reason to recreate virtual env each time. Skipping this part significantly speeds up testing
- add an option keep_env to cli. True means I want to keep my environment, not clean up
- check if the virtual env already exists. If it does, carry on
- manually tested

[PR-240] Skip virtual env creation if exits for testing

---

clarifai/runners/utils/url_fetcher.py

- Since we now have the `data.parts` proto, which supports multiple images and other inputs in a single request, we also need to downloading them as bytes in the API
*
*
*
*

Download data.parts as bytes in the API

---

clarifai/rag/rag.py

* User_id is not passed in the RAG init class, which is causing issue when uploading documents using RAG object inside ORG apps.
* This is for rag-chatbot module going to demo for airbus.
* Passed user_id in the init class
*
*

Added user_id in RAG init class

---

clarifai/runners/models/model_run_locally.py
clarifai/runners/models/model_upload.py

Minor Fixed for Model local testing

---

clarifai/datasets/upload/features.py
clarifai/datasets/upload/multimodal.py
clarifai/datasets/upload/text.py

* To support Data Ingestion Pipelines in clarifai-datautils library
* Made labels optional in dataloader

[DEVX-454]: Make Dataloader labels optional to support Data Ingestion Pipeline

---

clarifai/client/model.py

Model predictions are failing when using `generate_by_bytes` and `predict_by_bytes` methods to make predictions with any community model except for our own model that is configured with a dedicated compute_cluster_id and nodepool_id. 
This happens because the `generate_by_bytes` and `predict_by_bytes` methods use the model’s user_id to retrieve the `compute_cluster_id` and `nodepool_id` resources, but these resources cannot be found under the model’s user_id.
Now user has to pass their `user_id` in these prediction methods to work
*
*
*
*

[EAGLE-5371] Fix predictions methods

---

clarifai/runners/models/model_upload.py
clarifai/runners/utils/loader.py

HF token Validation

---

clarifai/runners/utils/loader.py

original folder contains files that are provided by the original uploader. HF creates their own checkpoints, hence we do not need this folder
Added an ignore_pattern to snapshot_download

[PR-295] Ignore pattern for original folder

---

clarifai/runners/models/model_run_locally.py
tests/runners/dummy_runner_models/1/model.py
tests/runners/dummy_runner_models/config.yaml
tests/runners/dummy_runner_models/requirements.txt
tests/runners/test_model_run_locally.py
tests/runners/test_model_test_locally.py

- Added tests for Model run locally within both virtual env and docker container
- Tests covers all the related function used in following command:
- `clarifai model test-locally --model_path <> --model env`
- `clarifai model test-locally --model_path <> --model container`
- I also fixed some edge cases for the `test-locally` and `run-locally` commands to ensure they work across all operating systems, and also works whether or not the user's system has a GPU.
*
*
*
*

[EAGLE-5342] Added Tests for  Model run locally

---

clarifai/runners/models/model_upload.py
tests/runners/hf_mbart_model/1/model.py
tests/runners/hf_mbart_model/config.yaml
tests/runners/hf_mbart_model/requirements.txt
tests/runners/test_model_run_locally.py
tests/runners/test_model_upload.py

- Added Model Upload tests
- Added Dummy HF model and added run-locally tests for HF model too
- Current tar function don't works in windows, so replacing it with Python's built-in `tarfile` module
*
*
*
*

[EAGLE-5342] Added Model Upload Tests

---

clarifai/client/input.py
clarifai/utils/misc.py
tests/compute_orchestration/configs/example_deployment_config.yaml
tests/runners/hf_mbart_model/config.yaml

* https://clarifai.atlassian.net/browse/DEVX-876
* Added a function to clean invalid Input IDs before pushing them

[DEVX-876]: Fixed Issue with Filename as Invalid Input ID

---

clarifai/cli/model.py
clarifai/client/input.py
tests/compute_orchestration/configs/example_deployment_config.yaml
tests/runners/hf_mbart_model/config.yaml
tests/test_data_upload.py

* To support multi-input models predictions
* get_input usage is removed from Model Predict CLI as unable to provide the app_id (given app_id is of model)
* Added get_input method to support Model Predict CLI in future
* Removed the exception part to guarantee single type of input
* Removed get_input usage in Model Predict CLI
* Added get_input method to Inputs class
* Added in tests/test_data_upload.py

[DEVX-896]: Update Model Predict CLI

---

clarifai/runners/models/model_run_locally.py
tests/runners/test_download_checkpoints.py
tests/runners/test_model_run_locally-container.py
tests/runners/test_model_run_locally.py

Avoid the runtime path as it'll clobber /tmp over and over write checkpoints into model_path/1/checkpoints as before for test-locally and unit tests.

use the non-runtime path for tests

---

clarifai/client/model.py

* Generate by bytes function wasn't working for the dedicated nodepool inference calls because the function is not considering user_id from the environment variable.

fixed user id bug in generate_by_bytes function

---

clarifai/runners/models/model_builder.py
clarifai/runners/utils/loader.py

* In SDK while validating HF checkpoints from config.yaml, we are doing a check to validate whether `config.json` present inside the `repo_id`.
* This is to essentially fetch concepts for image classification and segmentation type tasks, which is irrelevant for LLM and VLM models. Due to this some GGUF models from HF couldn’t able to be uploaded since it doesn’t have config.json in the repo.
* By just using the validation step to check if the current model type id is in `CONCEPTS_REQUIRED_MODEL_TYPE` list and only checks for `config.json` if it passes the condition.
* Not added at this point. But will add in future with dummy model with model type id in `CONCEPTS_REQUIRED_MODEL_TYPE`  without` config.json` and a lightweight `text-to-text` model without `config.json`.

Removed HF loader config.json validation for all clarifai Model type ids

---

clarifai/runners/models/model_class.py
clarifai/runners/utils/data_types.py
clarifai/runners/utils/method_signatures.py

In prep for `ruff check` across the repo, it flags some comparisons that should be `is`. Making a PR for just that first to see if it makes sense.

[EAGLE-6151]: change some == to is

---

clarifai/runners/models/model_class.py
clarifai/runners/utils/code_script.py
clarifai/runners/utils/data_utils.py
clarifai/runners/utils/method_signatures.py

- Fix code snippets code
- for when any of method argument Param(default=None)
- Included stream method code in snippet
- corrected code snippets  
- Support (default=None) is Param on client side, currently it isn’t supported
- Fixed Param Class, before it was not working with openai client
- Remove use of OutputInfo.params_specs for inference_params
*
*
*
*

[PR-590] Fix Pythonic bugs

---

clarifai/cli/model.py
clarifai/client/model.py
clarifai/runners/utils/code_script.py
clarifai/urls/helper.py
clarifai/utils/config.py
clarifai/utils/constants.py

This pull request introduces enhancements to the configuration handling, URL generation, and client script generation in the Clarifai codebase. The changes improve flexibility by introducing new default values, methods for constructing URLs for specific endpoints, and updated logic for generating client scripts based on context and method signatures.
* Added support for default fallback values (`DEFAULT_UI` and `DEFAULT_BASE`) in the `Context` class when environment variables are not set. This ensures a more robust configuration handling process.
* Updated `__getattr__` in `Context` to prioritize environment variables over configuration values and provide detailed error messages for missing attributes.
* Introduced `mcp_api_url` and `openai_api_url` methods in `ClarifaiUrlHelper` to …

[EAGLE-6237]: update code snippets for MCP/OpenAI and make env vars take precedence

---

clarifai/cli/model.py
clarifai/client/user.py
tests/test_list_models.py

Add list all models information
* To have a quick look of model like information such as if it supports openai api, model type, methods, etc...
* In python
```python
from clarifai.client import User
user = User()
user.list_models(show=True, user_id="openai") # default to current user
```
* CLI
```bash
clarifai model list
clarifai model list openai
```
Example output:
```
user_id    app_id           id                                model_type               url                                                                                  supported_openai_client    UNARY_UNARY    UNARY_STREAMING    STREAMING_STREAMING
---------  ---------------  --------------------------------  -----------------------  ----------------------------------------------------------------------------------- …
```

PR-649 - Add list models

---

clarifai/runners/server.py

The gRPC server mode and runner mode had inconsistent thread configuration defaults. The gRPC server used a hardcoded default of 32 threads for `pool_size`, while the runner mode respected the `CLARIFAI_NUM_THREADS` environment variable. This inconsistency made it difficult for users to configure thread scaling uniformly across different deployment modes.
- Updated the `--pool_size` argument default from hardcoded `32` to `os.environ.get('CLARIFAI_NUM_THREADS', 32)`
- Both gRPC server mode (`--grpc` flag) and runner mode (default) now use the same `CLARIFAI_NUM_THREADS` environment variable as their configuration source
- Maintains backward compatibility by keeping 32 as the fallback default when the environment variable is not set
- This is a backward-compatible change that only affects …

[PR-386] default to num_threads first

---

clarifai/cli/model.py
clarifai/runners/utils/code_script.py

This pull request includes updates to the `clarifai/runners/utils/code_script.py` file to improve string formatting and handle default values more robustly. The most important changes involve updating how `base_url` is formatted and refining the handling of iterators for string field types.
* Updated the `base_url` string formatting in `async def main()` to ensure the value is enclosed in single quotes, improving consistency and preventing potential issues with special characters. (`[clarifai/runners/utils/code_script.pyL130-R130](diffhunk://#diff-f990dbbc37fac6c569969b0e28e173a20b80fd30f5db1899e0f5b435b71f753dL130-R130)`)
* Modified the `_set_default_value` function to handle string field types (`str`) specifically when creating iterators, ensuring the default value is wrapped in single …

Fixed the Code Generation Script & Model CLI Description

---

clarifai/cli/model.py
clarifai/runners/server.py

Add flag default 1 for local dev runner threads. This helps keep the community plan at 2 hours of compute time usage.

[EAGLE-6403]: 1 default thread for local dev runner

---

clarifai/cli/templates/model_templates.py

This pull request updates the `clarifai/cli/templates/model_templates.py` file to provide placeholder implementations for prediction and generation methods and fixes an import path typo. Below are the key changes:
* Updated the `predict` method to return a placeholder response instead of a `pass` statement.
* Updated the `generate` method to yield a placeholder response instead of a `pass` statement.
* Corrected the import path for `Param` from `clarifai.runners.util.data_utils` to `clarifai.runners.utils.data_utils`.

Fixed Model Template Import &  Return Issues

---

clarifai/cli/base.py
clarifai/cli/model.py
clarifai/utils/cli.py

This pull request refactors the authentication and logging mechanisms in the Clarifai CLI to improve maintainability and user feedback. The key changes include replacing the `validate_pat_token` function with `validate_context_auth`, introducing structured logging via the `logger` module, and enhancing error handling and user feedback.
* Replaced `validate_pat_token` with `validate_context_auth` for validating context credentials, consolidating the logic and improving clarity. (`clarifai/cli/base.py`, `clarifai/utils/cli.py`) [[1]](diffhunk://#diff-6b11868a510d65b7b8d2550d7a614cfad49fc8e5d709a9ef529343281c74edffL162-R162) [[2]](diffhunk://#diff-e3cafb4277139ff82e1f80b80b5dcc839f4420b365d79d97c44206e151e6eeb1L177-R194)
* Updated the `validate_context_auth` function to use structured …

[PR-716]: Improve Handling for PAT and USER_ID

---

clarifai/cli/model.py

This pull request adds a new log message to the `local_runner` function in `clarifai/cli/model.py` to provide a direct link to the model's playground for easier interaction. 
Enhancements to logging:
* [`clarifai/cli/model.py`](diffhunk://#diff-87a0ccd1cdbf7bbe707ef7b0de9923fd510a6e9342671fc56306193799808040R878-R884): Added a log message with a URL to the model's playground, allowing users to chat with their model via a web interface. The URL includes parameters for the model ID, version ID, user ID, and app ID.

Added Playground URL to Local-Runner Logs

---

clarifai/cli/model.py
clarifai/utils/cli.py
tests/workflow/fixtures/single_branch_with_custom_cropper_model.yml

PR link - https://clarifai.atlassian.net/browse/PR-742
This pull request introduces enhancements to the `clarifai/cli/model.py` and `clarifai/utils/cli.py` files, focusing on improving dependency checks, model customization, and error handling for the Ollama toolkit. The most significant changes include the addition of utility functions for verifying prerequisites, relocating the `customize_ollama_model` function, and enhancing validation logic for toolkit-specific operations.
* Added `check_ollama_installed` function to verify if the Ollama CLI is installed. This function is now used in the `init` command to prevent execution when Ollama is missing. (`clarifai/utils/cli.py`, `clarifai/cli/model.py`) [[1]](diffhunk://#diff-87a0ccd1cdbf7bbe707ef7b0de9923fd510a6e9342671fc56306193799808040R12 …

Added local-runner requirements validation step

---

clarifai/runners/server.py

* Context is None for model runners, so they crash on the code snippet generation that assumes context is not None.
* Wrap the code generation in a condition on context not None.

[TP-1816]: skip code generation when context is None

---

clarifai/cli/model.py

Add the signatures from local runner when stating local runner. 
TODO after quick fix is to update / create a new model version if signatures change.

fix local runner signatures

---

clarifai/cli/model.py

* Restore 32 threads as default for local runner

[EAGLE-6429]: use 32 threads by default

---

clarifai/runners/models/model_builder.py

Sometimes it has an incorrect cached state.

Update model_builder.py to use --no-cache-dir when checking deps

---

clarifai/cli/model.py

The `clarifai model local-runner` command attempts to patch the latest existing version. If patching fails, or if no versions exist at all, a new version is created with the `local_dev` flag set to `True`.

[EAGLE-6656]:  Use latest local-dev model version in local runner

---

clarifai/runners/utils/code_script.py

Temperature rather than 1.0 has been deprecated for gpt-5 models

[PR-734] Use Method signature for local-runner (#718)
