clarifai/client/client.py
clarifai/client/mime_util.py
sample_main.py

Last night there was a bug filed with Exception generated while importing clarifai.client with Python3. Here is the preliminary fix for it. We should fix it for the Python3 users.

python3 compatible sample

---

clarifai/client/__init__.py
clarifai/client/client.py
tests/test_client.py

Let's let the server decide on what's supported or not instead of baking in options in the client.

refer to the server for languages

---

sample_main.py

make the result parseable by 3rd party tool like jq

output JSON string rather than the object

---

clarifai/client/client.py
setup.py

Adding color is new functionality without breaking backwards compatibility.
I also amended the doc string to remove Markdown.

bumping minor version number

---

clarifai/client/client.py
sample_main.py
tests/test_client.py

added support for usage API

---

README.md
clarifai/rest/client.py
setup.py

Thank you for providing a python API :). I wanted to play around with the custom training API using Python 3.5 but could not get the 2.0.11 to work because of this line (I guess a printing debug left over) : https://github.com/Clarifai/clarifai-python/blob/v2.0.11/clarifai/rest/client.py#L2064

Fix breaking print in the v2.0.11 release for python 3.X

---

.travis.yml
requirements.txt
tests/requirements.txt
tests/rest_tests/test_models.py
tests/unit_tests/mock_extensions.py
tests/unit_tests/test_concepts.py
tests/unit_tests/test_inputs.py
tests/unit_tests/test_invalid_respones.py
tests/unit_tests/test_model.py
tests/unit_tests/test_model_evaluation.py
tests/unit_tests/test_model_version.py
tests/unit_tests/test_predict.py
tests/unit_tests/test_search_concepts.py
tests/unit_tests/test_search_inputs.py
tests/unit_tests/test_search_models.py
tests/unit_tests/test_workflow.py

Previously these steps had to be done manually.
On next deployment make sure all works fine, otherwise adjust.

Deploy to PyPi and Github Releases via Travis

---

clarifai/rest/client.py

It's an empty list by default.

On creating a new model, always provide concepts

---

tests/rest_tests/test_public_models.py

Removed demographics model test as the model has been deprecated.

Removed demographics model test

---

tests/rest_tests/test_public_models.py

The model is internal only and old.

Remove segmentation model

---

.gitignore
.isort.cfg
.pre-commit-config.yaml
.pylintrc
.style.yapf
LICENSE
README.md
assert-code-quality.sh
requirements-dev.txt
requirements.txt
setup.py
sonar-project.properties

- Initial base structure of SDK
- `clarifai.client` will have all scripts requiring endpoint access

[DEVX:108] Base Structure of SDK

---

clarifai/errors.py
clarifai/utils/logging.py
clarifai/versions.py

- Rich based logging for errors, tracebacks, status, cli listing ..etc
- Manual test output

[DEVX:115] Base logging, Error handling setup

---

.github/workflows/run_tests.yml
requirements.txt
scripts/key_for_tests.py

- Added secrets for PAT to be used in model, workflow tests later

Added secrets for PAT

---

.github/workflows/run_tests.yml
README.md
clarifai/client/app.py
clarifai/client/base.py
clarifai/client/dataset.py
clarifai/client/lister.py
clarifai/client/model.py
clarifai/client/user.py
clarifai/client/workflow.py
scripts/key_for_tests.py
tests/test_app.py

- Automated Client [tests](https://github.com/Clarifai/clarifai-python/blob/5fc44f21bbafd037ebf36c3bd8207ded7baf5218/tests/test_app.py) flow for Interfacing - Apps , Inputs, Datasets ,Models , Workflows 
- Tests for the App class and its methods. CRUD operations are tested for each of the following resources:
- app (list, create, delete, read)
- dataset (create, delete)
- model (list, create, delete, read)
- workflow (list, create, delete, read)
- Add `url` initialise feature to app, dataset, model, workflow
```python
from clarifai.client.model import Model
model = Model("https://clarifai.com/anthropic/completion/models/claude-v2").predict_by_bytes(b"Write a tweet on future of AI", "text")
``` 
- Added `preserving_proto_field_name=True` key in `MessageToDict`

[DEVX-161] Client Interface Tests

---

clarifai/client/dataset.py
clarifai/client/input.py
clarifai/datasets/upload/base.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/loaders/imagenet_classification.py
clarifai/datasets/upload/text.py

- Reuse input functionalities in SDK(Datasets Interface)
- Updating methods in Inputs interface

[DEVX-117] Dataset_interface_update

---

README.md
clarifai/client/app.py
clarifai/client/base.py
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/lister.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/user.py
clarifai/client/workflow.py
clarifai/urls/helper.py
tests/test_app.py

- Added Modules interface (list, create, delete)
- Cleaned all doc strings to follow regular format for Sphinx docs
```python
from clarifai.client.app import App
app = App(user_id="user_id", app_id="app_id")
module = app.create_module(module_id="module_id", description="module_description")
all_modules = app.list_modules()
all_module_versions = module.list_versions()
app.delete_module(module_id="module_id")
```
- Added unit tests for create, delete of module
- Create/delete module version to be added later

[DEVX-183] Modules Interface

---

.github/workflows/run_tests.yml
clarifai/versions.py
docs/Makefile
docs/clarifai.rst
docs/conf.py
docs/index.rst
docs/install.rst
docs/tutorial.rst
docs/tutorial_predict.rst

- Added rst files for Sphinx based docs.

[DEVX-189] - rst Docs

---

clarifai/client/__init__.py
clarifai/versions.py
docs/conf.py
docs/requirements.txt
docs/tutorial_predict.rst
setup.py

- Added requirements to docs
- Added `rich` and `tqdm` to setup.py
- Added all clarifai.client classes to its __init__

Fix Doc Build bugs

---

README.md

>Slightly Changing layout
>Updated readme to point to
- clarifai python SDK docs
- clarifai SDK example repo
Preview image

[DEVX-185] update_readme

---

README.md
clarifai/client/dataset.py
clarifai/client/input.py

- Uploading data from URLs in a CSV
- Added all data types(image, text, audio, video)
- Uploading data through file_paths from CSV

[DEVX-128] upload URLs from CSV

---

README.md
clarifai/client/app.py
clarifai/client/dataset.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/user.py
clarifai/client/workflow.py
clarifai/datasets/upload/loaders/xview_detection.py
setup.py

- [remove model_id arg for create model version](https://github.com/Clarifai/clarifai-python/pull/177/commits/7a7d6fa1cf39dac71b071066879b863ae6606606)
- [Uncomment xview preprocessing step](https://github.com/Clarifai/clarifai-python/pull/177/commits/cc7a2342aa2b8bbd7abfc0e5cbd5b34871c7271e)
- [add schema to install](https://github.com/Clarifai/clarifai-python/pull/177/commits/6b55a21339c6d87c42e77edbd58c88328facefe0)
- [Update api docs reference](https://github.com/Clarifai/clarifai-python/pull/177/commits/c2ab29785623dab795eb2615f3231deb3237b440)
- [Fix DocString Info](https://github.com/Clarifai/clarifai-python/pull/177/commits/17d3804595eee4dfa13b383de75fe86aed2d53e5)

SDK improvements & Bug fixes

---

clarifai/client/workflow.py
clarifai/workflows/export.py
clarifai/workflows/utils.py
clarifai/workflows/validate.py

Contains minor bug fixes such as 
1. changing model id length from 32 to 48, 
2. fixing doc strings, 
3. yml format structure while exporting workflow
4. Fix KeyError in comparing output_info
- [change model id char len to 48](https://github.com/Clarifai/clarifai-python/commit/630ba463b5ce51c43fd9fa6c140a54126adb2ccf)
- [fix output_info compare bug](https://github.com/Clarifai/clarifai-python/commit/feba243d8947e509348f16748668f215863e3f82)
- [fix doc strings](https://github.com/Clarifai/clarifai-python/commit/aeab7689ac9906864de733c4afc232bb4b329a69)
- [fix yml format structure](https://github.com/Clarifai/clarifai-python/commit/20e56a7bbab62118036909ea79add3d71a1f56af)

Workflow create bug fixes

---

clarifai/client/input.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/loaders/imagenet_classification.py
clarifai/datasets/upload/text.py

[Input ID bug](https://clarifai.atlassian.net/browse/DEVX-208?atlOrigin=eyJpIjoiZWI2YmM1YmMyOGIxNDliNGE5OTRiNzNlYmY3MmQ4YWMiLCJwIjoiaiJ9)
- Random id as input ID while uploading from CSV for now.
- Imagenet loader input ID updated
- Receiving input ID from the CSV itslef.(When handling multiple columns from CSV)

[DEVX-208] Duplicate Input-ID Bug

---

README.md

- Add pypi downloads badge
- Replace slack with discord badge
- Arrange links such that it is less cluttered

Add badges and rearrange links

---

.pre-commit-config.yaml
.ruff.toml
clarifai/auth/helper.py
clarifai/client/app.py
clarifai/client/auth/helper.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/loaders/coco_segmentation.py
clarifai/datasets/upload/loaders/imagenet_classification.py
clarifai/errors.py
clarifai/models/model_serving/cli/repository.py
clarifai/models/model_serving/models/output.py
requirements-dev.txt
scripts/key_for_tests.py
tests/test_app.py
tests/test_data_upload.py
tests/test_modules.py

**Major change**
- Replace Autoflake with [Ruff](https://github.com/astral-sh/ruff):
> Beyond the defaults, Ruff re-implements some of the most popular Flake8 plugins and related code quality tools, including:
[autoflake](https://pypi.org/project/autoflake/)
- Disabled error E501 (lines too long) as there were too many. Will leave this for later
- Fix all other errors from Ruff
**Side changes**
- Fix some tests revealed by Ruff errors
- Timestamp added to app_id for some tests as it was likely that previous test failures did not clean up the app properly

Add Ruff to pre-commit hooks

---

clarifai/datasets/upload/examples/image_classification/cifar10/dataset.py
clarifai/datasets/upload/examples/text_classification/imdb_dataset/dataset.py
clarifai/datasets/upload/features.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/text.py

- Support metadata in dataloader
- Add metadata in dataclasses of all supported types(vls/text cls, obj, seg)
- Manual dataset upload

[DEVX-236] Support metadata in dataloader

---

clarifai/models/api.py
clarifai/models/model_serving/README.md
clarifai/models/model_serving/cli/deploy_cli.py
clarifai/models/model_serving/docs/inference_parameters.md
clarifai/models/model_serving/docs/model_types.md
clarifai/models/model_serving/model_config/config.py
clarifai/models/model_serving/model_config/inference_parameter.py
clarifai/models/model_serving/model_config/model_types_config/multimodal-embedder.yaml
clarifai/models/model_serving/model_config/serializer.py
clarifai/models/model_serving/models/default_test.py
clarifai/models/model_serving/models/inference.py
clarifai/models/model_serving/models/model_types.py
clarifai/models/model_serving/models/pb_model.py
clarifai/models/model_serving/models/test.py

[EAGLE-3552] - Add inference parameters:
* Modify model.py and inference.py to receives them
* Generate JSON file for uploading
* Test with inference parameters
* update doc
[EAGLE-3552] - add multimodal-embedder model type
[EAGLE-3552]: https://clarifai.atlassian.net/browse/EAGLE-3552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EAGLE-3552]: https://clarifai.atlassian.net/browse/EAGLE-3552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EAGLE-3552][EAGLE-3567] - Add inference params and multimodal-embedder model

---

tests/test_model_train.py

- Tests for model training and supported functionalities

[DEVX-223]: Tests for Model Training 

---

README.md

Add discord badge with chat number

Add chat number online badge

---

clarifai/constants/model.py
clarifai/utils/model_train.py
tests/test_model_train.py

- Removing internal only training params.
- Removing internal only training model type.
- Changing pytest test scripts according to it..

[DEVX-301]: Removing internal_only Training Params

---

.github/workflows/run_tests.yml

- Due to no access of secrets for external PRs

Skip tests for PRs from Forks

---

clarifai/models/model_serving/examples/multimodal_embedder/README.md
clarifai/models/model_serving/examples/multimodal_embedder/clip/1/inference.py
clarifai/models/model_serving/examples/multimodal_embedder/clip/1/model.py
clarifai/models/model_serving/examples/multimodal_embedder/clip/1/test.py
clarifai/models/model_serving/examples/multimodal_embedder/clip/config.pbtxt
clarifai/models/model_serving/examples/multimodal_embedder/clip/requirements.txt
clarifai/models/model_serving/examples/text_embedding/README.md
clarifai/models/model_serving/examples/text_embedding/instructor-xl/1/inference.py
clarifai/models/model_serving/examples/text_embedding/instructor-xl/1/model.py
clarifai/models/model_serving/examples/text_embedding/instructor-xl/1/test.py
clarifai/models/model_serving/examples/text_embedding/instructor-xl/config.pbtxt
clarifai/models/model_serving/examples/text_embedding/instructor-xl/requirements.txt

Split part of #227, add new model type example

[EAGLE-3698]-split- add new model type example

---

clarifai/client/runner.py
clarifai/runners/example.py
clarifai/runners/example_llama2.py

- lint fixes
- [limit num parallel polls to 10](https://github.com/Clarifai/clarifai-python/commit/c349c6f99fc6c2a88a4177d3f3acb2d0bfd2b799)

Fix updated runners

---

requirements.txt

Loosen requirement constraints

---

clarifai/client/input.py

Fix bug in input.py
```diff
-    if (image_bytes and image_url) or (not image_url and not image_url):
+    if (image_bytes and image_url) or (not image_bytes and not image_url):
```

Resove bug in get_multimodal_input fn

---

clarifai/rag.py
clarifai/rag/__init__.py
clarifai/rag/rag.py
tests/test_rag.py

**Beta**
New RAG class to streamline chat experience with a single interface.
Left the other methods as TODO so that other can work on it in parallel.
Tested manually. Note that rag-prompter is only public in dev at the moment. Can test with "prompter" model type.

[LT-4894] Add RAG class

---

clarifai/client/workflow.py

Increase Workflow Predict retry time from 60 sec to 10 minutes by adding 60*10 at line 88

Increase Workflow Predict retry time from 60 sec to 10 minutes

---

README.md
clarifai/rag/rag.py
tests/test_app.py

- Add Example snippet to README

Add RAG example on readme

---

clarifai/rag/rag.py

Allow specifying parameters like `min_score` via kwargs in RAG setup method.

use kwargs in RAG setup

---

clarifai/client/dataset.py
clarifai/datasets/upload/features.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/utils.py

- Upload status update: Subtracting the existing data stats in upload status
- support image bytes for annotation loaders(clarifai-datautils support)

[DEVX-343]: Update Upload status

---

.github/pull_request_template.md

- Added a short and easily readable PR template

PR_template

---

clarifai/client/model.py

Bring gRPC eval endpoints to SDK
Note: We currently don't have endpoint to retrieve eval metrics of specific model type

[EAGLE-3919] - eval endpoints 

---

README.md

Give the repo a star ⭐
*
*
*
*

Update README.md for Give the repo a star ⭐

---

clarifai/client/model.py
clarifai/utils/model_train.py

- Duplicate concept are created and Model Training failing while giving wrong concept ID to Training.
- List concepts and check if the given concepts are available in the App..

[DEVX-310]:  Concept ID check Model Training

---

clarifai/client/input.py
clarifai/rag/rag.py

1. user and now_ts variable scope bug fixes in RAG's setup()
2. added dataset_id param in RAG's upload()
3. added chunk sequence no in metadata during pdf upload in RAG
4. accepted custom metadata in upload()and added it to each chunk
5. made  rag-prompter's model id similar to that of rag workflow's
6. added patch_inputs() in inputs.py

Changes required for RAG module

---

clarifai/client/model.py

Return all fields in list_eval

Return all fields in list_eval

---

clarifai/client/app.py
clarifai/client/base.py
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/runner.py
clarifai/client/search.py
clarifai/client/user.py
clarifai/client/workflow.py

Add session-token as alternative authentication
To be able to use SDK in other hosted modules like `module-eval` as we pass to it a token instead of PAT
add `token` arg in `__init__` method

[EAGLE-4050]-consume-token

---

clarifai/models/model_serving/cli/build.py
clarifai/models/model_serving/cli/upload.py

build cli has failed to call test file in subprocess.run
add `shell=True` in subprocess.run

Fix file not found error in CLI test on Linux/Mac

---

clarifai/models/model_serving/cli/_utils.py
clarifai/models/model_serving/utils.py

* Fix call subprocess in list example cli
* Raise empty PAT and remind to login

Fix call subprocess

---

README.md

Description:
1. Updated readme with `retry_upload_from_logs` function examples.

[DEVX-366] Updated readme 

---

clarifai/client/app.py
clarifai/client/dataset.py
clarifai/datasets/export/inputs_annotations.py

Standalone function to get the request and get an archive zip url with input protos, that we can use to iterate inputs with annos and convert to other formats.

updates for data export

---

README.md
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/client/workflow.py
clarifai/utils/misc.py

* Add model export to README
* Update backoff iterator to support custom starting count, so different process can have different starting wait times.
| Old | New (BackoffIterator(10)) |
|-----|-----|
| 0.1 | 1.7921603940370006 |
| 0.64 | 2.329808512248101 |
| 1.28 | 3.028751065922531 |
| 2.56 | 3.937376385699291 |
| 5.12 | 5.118589301409078 |
| 10.24 | 6.654166091831802 |
| 20.48 | 8.650415919381343 |
| 10.24 | 11.245540695195746 |
| 10.24 | 14.61920290375447 |
| 10.24 | 19.004963774880814 |
| 10.24 | 24.706452907345057 |
| 10.24 | 32.118388779548575 |
| 10.24 | 41.75390541341315 |
| 10.24 | 54.280077037437096 |
| 10.24 | 70.56410014866823 |
| 10.24 | 91.7333301932687 |
| 10.24 | 119.25332925124931 |
| 10.24 | 155.0293280266241 |
| 10.24 | 201.53812643461137 |
| 10.24 | 261.9995643649948 …

Add model export to README

---

clarifai/client/app.py

* Related to recent model init changes #317 
*
* Existing tests should be pass
*

[DEVX-401] Create Workflow Bug

---

clarifai/client/app.py
clarifai/client/auth/helper.py
clarifai/client/base.py
clarifai/client/dataset.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/runner.py
clarifai/client/search.py
clarifai/client/user.py
clarifai/client/workflow.py
requirements.txt
tests/test_auth.py

* Adding root certificate support to establish secure gRPC connections.
* Adding root certificate param in all the classes and auth helper
* Updating the grpc to latest version
* Added a test to validate the root certificate path in test_auth.

[DEVX-400] Add root cert support

---

clarifai/client/model.py
clarifai/models/model_serving/cli/upload.py

* Enable `create model version by uploading local file using new endpoint `PostModelVersionUpload`
* Other updates: move current model upload method to clarifai module
* Implement `create_version_by_file` in Model class.
* Consume this feature in cli. Below is example usage.
```bash
$ clarifai upload model </path/to/your/project> --id model-id --user-app user-id/app-id
```

[EAGLE-3948] - Post model version upload

---

clarifai/models/model_serving/README.md
clarifai/models/model_serving/docs/cli.md

update upload cli doc

---

README.md
clarifai/client/search.py
clarifai/constants/search.py
tests/test_app.py
tests/test_search.py

* To add pagination feature in Search()
* [To add algorithm support in Search() ](https://clarifai.atlassian.net/browse/DEVX-413?atlOrigin=eyJpIjoiMzQzYTZmNmM0ZjU0NDNmZmI0NGQ0Y2YxYWY4MDI5ZTQiLCJwIjoiaiJ9)
* Added `pagination` switch param in Search() class for pagination.
* Added `per_page` and `page_no` params in Search.query() for pagination.
* Added `algorithm` param in Search() for switching between search algorithm
* Added pagination tests for Search()

[DEVX-411]: Adding Pagination in Search

---

clarifai/rag/rag.py
clarifai/rag/utils.py
tests/requirements.txt

* RAG.setup() fails if we delete a specific workflow and give the same id.
* [RAG.upload() to support folder of text files.
](https://clarifai.atlassian.net/browse/DEVX-393?atlOrigin=eyJpIjoiMTMxZTE5ZDMwMDMyNDZhOWI5ODRlN2QwZmJhNjU1MjMiLCJwIjoiaiJ9)

[DEVX-412]: RAG model_id bug

---

clarifai/rag/utils.py

* RAG.upload() fails with error message `Unable to import PDFReader`
* Changing llama-index-core version to 0.10.24 in user message

[DEVX-416]: RAG upload debug

---

clarifai/client/input.py
clarifai/datasets/upload/features.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/loaders/coco_captions.py
clarifai/datasets/upload/loaders/coco_detection.py
clarifai/datasets/upload/text.py

* Support both class ID and name for labels
* Added `label_ids` param in Dataloaders and support for it in input functions.

[DEVX-419]: Adding ID support for labels

---

README.md
clarifai/client/input.py

* PR opened with reference to https://clarifai.atlassian.net/browse/DEVX-421
*  Failed annotations are not capturing the full details of failure in the log.
* Not needed

DEVX-421-modified to catch detailed failed annotations status

---

CHANGELOG.md
tests/test_app.py

- Modified changelog with PR https://github.com/Clarifai/clarifai-python/pull/342. 
- Removed runner tests for now

Update CHANGELOG.md with PR #342

---

clarifai/client/auth/helper.py
clarifai/client/auth/stub.py
clarifai/client/base.py
clarifai/client/model.py
tests/test_auth.py
tests/test_search.py

- Support streaming endpoints GenerateModelOutputs or StreamModelOutputs from the stub
-  Easier to setup client from env and just use it's stub like: 
```
from clarifai.client import BaseClient
client = BaseClient.from_env()
stub = client.Stub
response = stub.PostModelOutputs(...)
```
- Remove validation of app_id   as the base client
*
*
*
*

[EAGLE-4453] Stream support

---

clarifai/constants/dataset.py
clarifai/datasets/export/inputs_annotations.py
tests/test_app.py

* Dataset exports are failing via SDK - either creating empty directories or a malformed zip
* To resolve this used the class input session with an authentication header when downloading the export
* Added the test **test_export_dataset** to tests/test_app.py file to test both creation of dataset versions as well as dataset export

[DEVX-479]: Dataset Export Bug

---

clarifai/client/input.py
tests/test_data_upload.py

- Patch Operations Addition for Input Annotations & Concepts
- Input proto bug fix
* To patch the existing input annotations & concepts
* Ref : https://clarifai.atlassian.net/browse/DEVX-469
* To avoid errors avail patching inputs
* Create a function each for patching input annotations & concepts using Clarifai Grpc library
* Changed the dataset_id argument of _get_proto function from positional argument to optional argument for ease of usage

[DEVX-469]: Patch Operations Addition for Input Annotations & Concepts

---

clarifai/utils/logging.py

* Refer https://clarifai.atlassian.net/browse/DEVX-516
* By adding a constant width value to rich logging to maintain this width irrespective of IDE width
* Ref : https://stackoverflow.com/a/72600451

[DEVX-516]: Improve Rich Logging by Width Addition

---

clarifai/client/app.py
clarifai/client/base.py
clarifai/client/user.py
tests/test_app.py

* To patch the existing input annotations & concepts
* Ref : https://clarifai.atlassian.net/browse/DEVX-520
* Created a function each for patching Apps & Datasets using Clarifai Grpc library in User Class file & App Class file respectively
* Added tests for Patch Operations of Apps and Datasets in tests/test_app.py

[DEVX-520]: Patch Operations Addition for Apps and Datasets

---

clarifai/client/search.py
tests/test_search.py

* https://clarifai.atlassian.net/browse/DEVX-326 - Using 2 types of search request from SDK potentially blocks the users to use different types of filters altogether. Filters like `metadata`, `concepts` , `geo-location` can't be used along with `input_types`, `input_dataset_ids` etc due to former comes under `Annotation` proto and latter comes under `Input` proto.
* https://clarifai.atlassian.net/browse/DEVX-546 - Using `PostAnnotationsSearches` also returns duplicated triplets due to some default reasons, which is listed [here](https://clarifai.slack.com/archives/CK3QXM78Q/p1701841567690739) . 
* By appropriately packing the filters with their associate proto and passing it to `PostInputsSearches` function to achieve this.
* Added a test function inside tests/test_search.py named …

DEVX-326 - Removed PostAnnotationsSearches from SDK search to avoid duplicated results

---

clarifai/client/app.py
tests/test_app.py
tests/workflow/test_create_delete.py

* To patch the existing Models & Workflows
* Ref : https://clarifai.atlassian.net/browse/DEVX-521
* Created a function each for patching Models and patching Workflows using Clarifai Grpc library in App Class file
* Added tests for Patch Operations of Models & Workflows in tests/test_app.py & test/workflow/test_create_delete.py respectively

[DEVX-521]: Patch Operations for Models & Workflows

---

clarifai/client/app.py
clarifai/utils/logging.py
clarifai/utils/misc.py
tests/test_app.py
tests/workflow/test_create_delete.py

* To support Create, List and Delete Concept Relations for a App
* Ref : https://clarifai.atlassian.net/browse/DEVX-538
* Created a function each to create, list and delete concept relations for the app
* Also added a function to add concepts for the app
* Added tests for creation, listing and deletion of concept relations of a app in tests/test_app.py

[DEVX-538]: Addition of Concept Relation Operations

---

clarifai/client/app.py

* To get the count of all inputs present in app.
*  https://clarifai.atlassian.net/browse/DEVX-598
* Created a function to get the inputs count of an app.

[DEVX-598]: Get App's Input Count

---

clarifai/datasets/export/inputs_annotations.py

* Exporting annotation data of class concept or bounding box info (priority to class concept) [any one only]
* Exporting annotation data of whatever present data(concept as well as bbox)

[DEVX-605]: Dataset Annotations Export Bug Resolution

---

clarifai/client/app.py

* A bug resolution to function name change

[DEVX-539]: Bug Resolution

---

clarifai/datasets/export/inputs_annotations.py

* If detection annotation not present return empty list

fix dataset annotation export issue

---

clarifai/runners/dockerfile_template/Dockerfile.cpu.template
clarifai/runners/dockerfile_template/Dockerfile.cuda.template
clarifai/runners/models/model_upload.py
clarifai/runners/utils/loader.py

- Added HuggingFaceLoader in utils
- Added methods in model_upload for download_checkpoints and handling concepts for classification, detection models
- Changed `--model_path` flat in `model_upload.py` inplace of `-folder`
*
*
*
*

[EAGLE-4744] Added Hf loader and Handled Concepts in model upload

---

clarifai/runners/utils/data_handler.py

- Remove pydantic dependency from runners in clarifai-python
*
*
*
*

[EAGLE-4962] Remove pydantic dependency

---

clarifai/runners/utils/loader.py

- Added validation check in HF loader, if the checkpoints really exit at checkpoint path
*
*
*
*

Add validation check in HF loader

---

clarifai/client/dataset.py
clarifai/constants/dataset.py
clarifai/datasets/upload/base.py
clarifai/datasets/upload/features.py
clarifai/datasets/upload/image.py
clarifai/datasets/upload/multimodal.py
clarifai/datasets/upload/text.py
clarifai/utils/misc.py

* To aid the [DEVX-583](https://clarifai.atlassian.net/browse/DEVX-583) - Adding multimodal loader support for `clarifai-python-datautils` package. 
* Reference [PR](https://github.com/Clarifai/clarifai-python-datautils/pull/11) in `clarifai-python-datautils` repo.
* Modified the error logging in retrying the failed uploads to log either text or image. (`clarifai/client/dataset.py`)
* Added `MultiModalFeatures` and `MultiModalLoader` task support in clarifai-python.
* Tested locally in `clarifai-python-datautils` repo as integration.
[DEVX-583]: https://clarifai.atlassian.net/browse/DEVX-583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVX-583-Added MultiModalLoader support

---

requirements.txt

- Added `fsspec` dependency which would be required in runners for model upload 
*
*
*
*

Added fsspec dependency

---

clarifai/runners/models/model_upload.py
clarifai/runners/utils/loader.py

Able to use the download functionality on it's own.

Download refactor

---

clarifai/client/app.py
clarifai/client/compute_cluster.py
clarifai/client/dataset.py
clarifai/client/deployment.py
clarifai/client/input.py
clarifai/client/model.py
clarifai/client/module.py
clarifai/client/nodepool.py
clarifai/client/user.py
clarifai/client/workflow.py
clarifai/datasets/export/inputs_annotations.py
clarifai/rag/rag.py
clarifai/runners/models/model_upload.py
clarifai/runners/server.py
clarifai/runners/utils/loader.py
clarifai/runners/utils/logging.py
clarifai/runners/utils/url_fetcher.py
clarifai/utils/evaluation/helpers.py
clarifai/utils/evaluation/main.py
clarifai/utils/logging.py

Fixed issue comparing files in checkpoints. 
Unified all the logging to make it simpler and use an optional env var LOG_LEVEL to define what level to log at.

improve logging and checkpoint download

---

clarifai/client/deployment.py
clarifai/client/model.py
clarifai/client/nodepool.py

- Updated predict endpoints  (predict, generate and stream)  with RunnerSelector proto argument 
```python
Example:
>>> from clarifai.client.model import Model
>>> model = Model("url") # Example URL: https://clarifai.com/clarifai/main/models/general-image-recognition
or
>>> model = Model(model_id='model_id', user_id='user_id', app_id='app_id')
>>> stream_response = model.generate_by_url('url', 'image', deployment_id='deployment_id')
>>> list_stream_response = [response for response in stream_response]
OR 
>>> from clarifai.client.model import Model
>>> model = Model("url") # Example URL: https://clarifai.com/clarifai/main/models/general-image-recognition
or
>>> model = Model(model_id='model_id', user_id='user_id', app_id='app_id')
>>> stream_response = model.generate_by_url('url', …
```

[EAGLE-4921] Update predict endpoints with RunnerSelector

---

clarifai/runners/models/model_upload.py
clarifai/runners/utils/loader.py

- handling missing huggingface_hub package
- Manually tested

[PR-161] import HF handling

---

clarifai/client/dataset.py
tests/test_data_upload.py

* To add a functionality to merge datasets using SDK
* Used PostDatasetInputsRequest grpc. endpoint to merge a dataset Y into dataset X as follows:
`X = PostDatasetInpust(dataset_id=X, query=filter{dataset=Y}}`
* Added test in `tests/test_data_upload.py`

[DEVX-571]: Added functionality to Merge Datasets

---

clarifai/runners/dockerfile_template/Dockerfile.cuda.template
clarifai/runners/models/model_upload.py
clarifai/runners/utils/loader.py
tests/runners/test_runners.py

* Only download HF config.json file instead of downloading complete model checkpoints to infer the concepts
* Improving logging
* Fixed model-upload bug when checkpoints not specified in config.yaml
*
* Tested Manually
*

Improve UX for model upload

---

tests/requirements.txt

* Security update: Bumping llama index version
* https://github.com/Clarifai/clarifai-python/security/dependabot
* Existing tests are sufficient

Bump llama version

---

clarifai/client/input.py
clarifai/datasets/upload/utils.py
tests/test_data_upload.py

* To remove unnecessary prefixes to concept ID added from SDK
* Remove the 'id-' prefix added to concept ID using SDK
* Already present

[DEVX-572]: Removing 'id-' prefix from concept ids from SDK

---

tests/compute_orchestration/test_crud_operations.py

* Test CRUD operations of CO Resource - Deployment
* Added tests in the `tests/compute_orchestration/test_crud_operations.py`
* Added

[DEVX-691]: Adding Tests for CO Resource - Deployment

---

clarifai/cli/base.py
clarifai/cli/model.py
clarifai/runners/models/model_run_locally.py
clarifai/runners/models/model_upload.py
clarifai/utils/cli.py
requirements.txt
setup.py
tests/test_app.py

- Clarifai CLI based on [Design Doc](https://clarifai.atlassian.net/wiki/spaces/DevX/pages/3897262124/Clarifai+Python+SDK+CLI+Design)
- Implemented `Model upload`, `Model test locally` and `Run model locally` in the CLI
```bash
clarifai model upload --model_path <model_path>
```
```bash
clarifai model test-locally --model_path <model_path>
```
```bash
clarifai model run-locally --model_path <model_path>
```
* Improve User experience of using SDK
*
* Locally tested 
*

[EAGLE-4917] CLI for Model upload

---

clarifai/client/auth/helper.py

* If None is passed as base_url, auth helper is running into an string error
* Added a check for the base param, if its None, will assign DEFAULT_BASE_URL

Debug Base URL

---

clarifai/client/input.py
tests/test_data_upload.py

* To provide functionality to delete annotations as per user requirements
* Added a function in **Input** class of `clarifai/client/input.py` to delete annotations using clarifai-grpc library
* Added in `tests/test_data_upload.py` file

[DEVX-824]: Added Delete Annotations Feature

---

clarifai/client/dataset.py

* Adding dataset.list_inputs() for ease of use
* Reused the Inputs.list_inputs() function internally in Dataset class
* Existing tests are sufficient

Adding list_inputs() function in dataset class

---

clarifai/client/deployment.py

* To fix a code bug related to selecting runner using deployment
* Minor code changes

[DEVX-825]: Fix Deployment RunnerSelector Bug

---

.github/workflows/run_tests.yml

* Tech Debt - https://clarifai.atlassian.net/browse/DEVX-718
* Adding Codecoverage test report in PRs.
* Modified `run_tests.yml` to add the summary report in markdown table in the comments of PRs, For every commit the table will be updated rather a new comment.

DEVX-718 Codecoverage report summary in PRs

---

clarifai/client/model.py
clarifai/runners/models/base_typed_model.py
tests/runners/dummy_runner_models/model.py
tests/runners/dummy_runner_models/model_wrapper.py
tests/runners/test_anymodel.py
tests/runners/test_runners.py
tests/runners/test_textmodel.py

- Added tests for all stream and generate methods by starting the local dev runner
- Added tests for passing inference parameters to runners
*
*
*
*

[EAGLE-4467][EAGLE-4497] Add streaming tests and passing inference parameters to runners tests

---

clarifai/runners/models/model_run_locally.py
clarifai/runners/models/model_upload.py

- Changed the default env to prod for Model upload, since we are closer to launch
- download URL in API in form of bytes in test-locally
*
*
*
*

Change the default env to prod for Model upload

---

.github/workflows/run_tests.yml

* To fix the bug in run_tests.yaml workflow
* Correcting the condition for Periodic checks
*
*

Fix Periodic Tests

---

clarifai/datasets/export/inputs_annotations.py

* Fill zero to the bounding box values if its not in the proto(Meaning its in the edge of the image)
* Tested in Local, Existing test are sufficient!

Debugging dataset Export

---

clarifai/cli/model.py

* For ease of model prediction using CLI
* Adding predict command for model CLI submodule
* Already exists

[DEVX-839]: CLI support for Model Predict

---

README.md

Update README.md for Compute Orchestration

---

requirements.txt

* To restrict the protobuf version by clarifai-grpc library
* Removing the protobuf from requirements.txt

[DEVX-859]: Update Requirements to Resolve Conflicts

---

clarifai/runners/models/model_upload.py
clarifai/runners/utils/const.py

- Updated available torch images and did some refactoring
*
*
*
*

Updated available torch images and some refactoring

---

clarifai/runners/dockerfile_template/Dockerfile.template

- Update Dockerfile template for Sglang to make it work
*
*
*
*

[EAGLE-5324] Update Dockerfile for Sglang

---

clarifai/runners/models/model_upload.py
requirements.txt

- Added Model building log 
*
*
*
*

[EAGLE-5259] Add Model building logs

---

clarifai/client/dataset.py

* When called from the upload_dataset with dataloader consists of image bytes the error is not catching properly. So added a failsafe checks and improved error logging.

Improved error logging

---

clarifai/utils/logging.py

[EAGLE-5352]: Env var to exclude other json logger fields.

---

clarifai/runners/utils/loader.py

[PR-297] Extend ignore to subfolders

---

.github/workflows/run_tests.yml
clarifai/runners/models/model_run_locally.py

Added CLARIFAI_API_BASE in the test container

---

clarifai/runners/models/model_upload.py
clarifai/runners/utils/const.py

Updated Torch version Images and Delete tar file for every upload

---

tests/compute_orchestration/configs/example_deployment_config.yaml
tests/runners/hf_mbart_model/config.yaml

* CO backend change not supporting v2 model going forward: https://github.com/Clarifai/clarifai/pull/18890/files
* https://clarifai.atlassian.net/browse/WFP-902
* Uploaded a V3 test-upload model to clarifai platform
* Updated the deployment config file with V3 model details

[WFP-902]: Fixed Deployment Tests

---

clarifai/runners/utils/loader.py

HF checkpoints error resolve

---

clarifai/runners/models/model_run_locally.py

- Model Test/ Running locally failed within container due to New Dockerfile
*
*
*
*

[EAGLE-5500] Fixed Docker test locally

---

.github/workflows/run_tests.yml
tests/runners/test_model_run_locally-container.py
tests/runners/test_model_run_locally.py

[EAGLE-5424] Added Docker tests 

---

clarifai/runners/models/model_run_locally.py

The logic is unable to enter logger error logic

[PR-306] PAT feedback

---

clarifai/runners/models/model_builder.py
clarifai/runners/models/model_run_locally.py
clarifai/runners/utils/const.py
tests/runners/test_download_checkpoints.py
tests/runners/test_model_run_locally.py

Local test takes any as argument
This doesn't fully fix the problem with download_checkpoints but better than "any" failure. 
Properly throw error with incorrect python version. 
Do not tar up .pyc or `__pycache__` folders.

[PR-328] fix local tests

---

clarifai/runners/models/model_builder.py
clarifai/runners/server.py
tests/runners/test_num_threads_config.py

Introduce `num_threads` in config.yaml enabling setting multiple threads serving. Previously can be set only by `CLARIFAI_NUM_THREADS` env variable. 
* Keep it in config.yaml is easier to config, maintain and debug.
* Improve RPM to handle concurrent requests more efficiently.
The variable can be set through the environment or via the `num_threads` in config.yaml, with config.yaml taking priority over the environment variable.
* add test case

[PR-388] Add num_threads setting for serving

---

clarifai/runners/models/model_builder.py

* Display Model Upload Failed details
*
*
*

Display Model Upload Failed details

---

clarifai/cli/model.py
clarifai/runners/dockerfile_template/Dockerfile.template

Specify model_path by positional arg
* make our cli shorter
* `model_path` as positional arg with default value is current directory
```
clarifai model upload --model_path ./your/model/path
clarifai model upload ./your/model/path
cd ./your/mode/path
clarifai model upload
```
*
*

[PR-394] Specify model_path by positional arg

---

tests/compute_orchestration/configs/example_deployment_config.yaml

* `E      +  where 1 = <Result Exception(code: DEPLOYMENT_INVALID_ARGUMENT\ndescription: "Invalid deployment argument"\ndetails: "\'AutoscaleCo...or equal to \'AutoscaleConfig.ScaleDownDelaySeconds\'."\nreq_id: "sdk-python-11.1.6-722981b8213c4eefb60333316c70a3ef"\n)>.exit_code
`
* Update with `scale_to_zero_delay_seconds` param
*
*

update deployment_config 

---

clarifai/runners/models/model_builder.py
tests/runners/test_num_threads_config.py

* `num_threads` value is currently set to 1 in by default and have to set from config.yaml which is not documented yet. So to observe good performance on concurrent requests, setting it to 16 by default.
https://clarifai.slack.com/archives/C01KL1RUTDH/p1741709746346789?thread_ts=1741709508.217109&cid=C01KL1RUTDH
* Setting the field to 16 by default.

Modified num_threads to 16 in server.py

---

clarifai/runners/models/model_builder.py
clarifai/runners/models/model_run_locally.py
requirements.txt
tests/runners/test_model_run_locally-container.py
tests/runners/test_model_run_locally.py

* To test out models locally, we need not need Clarifai user_id, app_id, PAT
* https://clarifai.atlassian.net/browse/PR-402
* https://clarifai.atlassian.net/browse/PR-403
* Removed the assertions for user_id and app_id for `clarifai model run_locally` CLI command
* Removed the error logs when PAT is missing for `clarifai model run_locally` CLI command
* Added `aiohttp` library to avoid a error (https://clarifai.atlassian.net/browse/PR-402?focusedCommentId=89232)
* Updated the tests as required

[PR-402]: Fix 'clarifai model run-locally' to be independent of clarifai access

---

clarifai/cli/base.py

* To improve error handling related to CLI config
* https://clarifai.atlassian.net/browse/PR-416
* Ensure CLI config includes base_url after `clarifai login`
* https://clarifai.atlassian.net/browse/PR-417
* At base command, added a snippet to invoke `clarifai login` if config not set
* Added the prod base_url as default
* Additionally, changed the config file location from `current directory` to `$HOME/.clarifai`
*
*

[PR-416]: Fix CLI Config Issues

---

.github/workflows/requirements.txt
CHANGELOG.md
requirements.txt
tests/runners/test_runners.py

- Improved CLI login module [(#535)] (https://github.com/Clarifai/clarifai-python/pull/535)
- Updated the CLI to test out model locally independent of remote access [(#534)] (https://github.com/Clarifai/clarifai-python/pull/534)
- Modified the default value of `num_threads` field [(#533)] (https://github.com/Clarifai/clarifai-python/pull/533)

VERSION 11.2.0

---

clarifai/cli/base.py
clarifai/cli/compute_cluster.py
clarifai/cli/deployment.py
clarifai/cli/model.py
clarifai/cli/nodepool.py
clarifai/utils/cli.py

* Run validation for CLI config only when necessary
* Added a utility function to validate if config data exist
* Called this utility function in commands where config is necessary
*
*

Added Validation for CLI config

---

clarifai/client/app.py
clarifai/runners/models/model_builder.py
clarifai/runners/models/model_run_locally.py
clarifai/runners/utils/loader.py
tests/runners/test_download_checkpoints.py
tests/runners/test_model_run_locally.py

* To download only required files from huggingface repo
* By adding list of regex patterns to allow & ignore to model config
*
*

[PR-470]: Added Regex Patterns to Filter Checkpoint Files to Download

---

clarifai/runners/models/model_builder.py

* Broken model upload when no checkpoints in config
*
*
*

[EAGLE-5930]: Fix return values in model builder to fix model upload

---

clarifai/runners/models/model_run_locally.py

* Stream test not working for Test-Locally of CLI
* Ensured that data gets dowloaded from urls into bytes for stream request also
*
*

Fixed the Test-Locally Stream Test Request

---

clarifai/client/auth/stub.py
clarifai/client/dataset.py
clarifai/utils/logging.py
tests/runners/test_runners.py

fix some imports around logging

clean up some logging

---

clarifai/client/deployment.py
clarifai/client/model.py
clarifai/client/nodepool.py
clarifai/utils/protobuf.py
requirements.txt
tests/cli/test_compute_orchestration.py

Test cases fix

---

clarifai/runners/models/model_builder.py

* To use special subclasses like VisualDetectorClass or VisualClassifierClass in Model Upload
* Use indirectly inherited classes (like VisualDetectorClass or VisualClassifierClass) in model upload
*
*

[PR-556]: Adding usage of subclasses of ModelClass in Model Upload

---

tests/runners/hf_mbart_model/requirements.txt

[Vulnerability](https://github.com/Clarifai/clarifai-python/security/dependabot/33)

[PR-557] Update torch

---

.github/workflows/run_tests.yml
pyproject.toml
requirements-dev.txt
setup.py
tests/requirements.txt

Fix pyproject.toml

---

clarifai/runners/models/visual_detector_class.py

* To support users uploading visual detector models to platform
* Added a base class for visual detection model for pre & post processing stuff
*
* https://clarifai.atlassian.net/browse/PR-565

[PR-506]: Addition of Base Class for Visual Detector Models

---

clarifai/runners/models/model_builder.py
clarifai/runners/models/visual_detector_class.py
clarifai/runners/utils/code_script.py

- Spitting out client script after model upload
Model Upload Logs looks like below:
```python
2025-05-13 08:10:48.311851 INFO: Done building image!!! |  thread=8577109120 
[INFO] 13:40:52.350261 Model build complete! |  thread=8577109120 
[INFO] 13:40:52.350636 Build time elapsed 12.1s) |  thread=8577109120 
[INFO] 13:40:52.350853 Check out the model at https://clarifai.com/luv_2261/test-upload/models/test-code-snippet version: e84a5ebe171344d38adc3902ec355604 |  thread=8577109120 
[INFO] 13:40:52.356157 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
|  thread=8577109120 
[INFO] 13:40:52.356732 
import os
from clarifai.client import Model
from clarifai.runners.utils import data_types
model = …
```

Print script after model upload

---

clarifai/runners/models/visual_classifier_class.py
clarifai/runners/models/visual_detector_class.py

* To support users uploading visual classifier models to platform
* Added a base class for visual classification models for pre & post processing stuff
*
* Ref - https://clarifai.atlassian.net/browse/PR-507

[PR-507]: Addition of Base Class for Visual Classifier Models

---

clarifai/runners/__init__.py
clarifai/runners/models/__init__.py
tests/requirements.txt
tests/runners/dummy_runner_models/requirements.txt
tests/runners/hf_mbart_model/requirements.txt

cleanup fastmcp

---

clarifai/cli/model.py
clarifai/client/model.py
clarifai/client/user.py

* Refer here: https://github.com/Clarifai/clarifai-python/pull/557#:~:text=is%20AI%27%5D)-,User_id%20Bug,-Debugged%20a%20known

[PR-539] User ID bug in Model init()

---

clarifai/client/app.py
clarifai/client/model.py
clarifai/runners/dockerfile_template/Dockerfile.template
clarifai/runners/utils/const.py
clarifai/workflows/export.py
tests/workflow/fixtures/general.yml
tests/workflow/fixtures/multi_branch.yml
tests/workflow/fixtures/single_branch_with_custom_cropper_model-version.yml
tests/workflow/fixtures/single_branch_with_custom_cropper_model.yml
tests/workflow/fixtures/single_branch_with_public_cropper_model.yml
tests/workflow/fixtures/single_branch_with_public_cropper_model_and_latest_version.yml

Bumped to latest base images that have uv in them.

[EAGLE-6013]: use uv in the build process

---

clarifai/runners/models/model_builder.py
tests/runners/test_model_upload.py

Show a terminal prompt asking users if they want to create a new app when the specified app does not exist.
*
*
*
*

PR-652 - App action for model upload

---

clarifai/utils/constants.py
clarifai/utils/misc.py

Failed to run clarifai cli on Windows because variable `HOME` does not contain windows home path.
Use `pathlib.Path.home()` instead.

Fix path windows

---

clarifai/cli/model.py
clarifai/utils/constants.py
clarifai/utils/misc.py

This pull request introduces significant enhancements to the GitHub repository handling functionality in the `clarifai` CLI. The changes include the integration of a new `GitHubDownloader` class for robust GitHub folder downloads, modifications to the `init` method to support this new functionality, and the removal of redundant options. Additionally, the `GitHubDownloader` class provides advanced features like retry mechanisms, folder structure validation, and detailed error handling.
* **New `GitHubDownloader` Class**: Added a comprehensive class in `clarifai/utils/misc.py` to handle GitHub folder downloads with features like retry strategies, folder structure validation, and detailed error reporting. This replaces the need for custom logic in individual methods.
* **Integration in …

Add github folder download support and toolkit option in model init

---

.github/workflows/maintainer_tests.yml
pytest.ini
tests/runners/dummy_vllm_models/1/model.py
tests/runners/dummy_vllm_models/config.yaml
tests/runners/dummy_vllm_models/requirements.txt
tests/runners/test_vllm_model_upload.py

* Current tests workflow in the SDK covers all the functionality and basic tests to simulate the upload model and run model, but we needed an integrated unit tests for each toolkit for model upload.
* This pull request introduces a new workflow for maintainer-specific tests, adds support for a vLLM-based OpenAI-compatible server, and implements end-to-end testing for model uploads using dummy configurations. Key changes include the addition of a GitHub Actions workflow, a new model class for vLLM integration, configuration and dependency files, and comprehensive test cases.
* **Workflow and Testing Enhancements**:
.github/workflows/maintainer_tests.yml: Added a new GitHub Actions workflow for maintainer-specific tests, triggered manually via workflow_dispatch. This workflow sets up Python …

PR-323 Unit tests for toolkits.

---

clarifai/cli/base.py
clarifai/cli/pipeline.py
clarifai/cli/templates/pipeline_step_templates.py
clarifai/cli/templates/pipeline_templates.py
clarifai/client/pipeline.py
clarifai/runners/pipelines/pipeline_builder.py
clarifai/utils/config.py
tests/cli/test_pipeline.py

This pull request introduces several improvements and updates to the `clarifai/cli` codebase, focusing on enhancing command-line interface usability, improving logging practices, and simplifying configuration management. Below is a summary of the most important changes:
* Added shorter aliases for existing CLI commands, such as `'ls'` for `list-contexts`, `'use'` for `use-context`, `'current'` for `current-context`, `'create'` for `create-context`, and `'delete'` for `delete-context` in `clarifai/cli/base.py`. These changes improve the user experience by providing more concise command options. [[1]](diffhunk://#diff-6b11868a510d65b7b8d2550d7a614cfad49fc8e5d709a9ef529343281c74edffL125-R125) [[2]](diffhunk://#diff-6b11868a510d65b7b8d2550d7a614cfad49fc8e5d709a9ef529343281c74edffL164-R164) …

various fixes for pipelines

---

clarifai/client/nodepool.py
clarifai/runners/utils/code_script.py

Fix nodepool creation

---

clarifai/runners/server.py

Fix API URL in local-runner

---

clarifai/utils/secrets.py

* BE changed to no longer support hot reloading, but we should still inject secrets from the environment into the request
* If no secret directory specified, pull secrets from environment and inject into request. Filter out env variables that start with `CLARIFAI`.
* Existing tests pass
*

[EAGLE-6114] Support secret injection into requests without secret files
